name: ArcherGames
version: 0.1
main: com.araeosia.ArcherGames.ArcherGames
depend: [Vault, VanishNoPacket, Votifier, WorldBorder]

commands:
  vote:
    description: Displays the voting links to vote on.
    usage: /vote
  chunk:
    description: Reloads chunks to stop ghost blocks.
    usage: /chunk
  ride:
    description: Right click to sit on someone.
    usage: /ride
  chat:
    description: Disables or enables chat.
    usage: /chat
  track:
    description: Track player statistics.
    usage: /track <player>
  who:
    description: Track players that are in game.
    usage: /who
    aliases: [players, online]
  money:
    description: Checks wallet balance.
    usage: /money
  baltop:
    description: Shows the players with the most money.
    usage: /baltop
  credtop:
    description: Shows the players with the most credits.
    usage: /credtop
  wintop:
    decription: Shows the players with the most wins.
    usage: /wintop
  stats:
    description: Shows a specified player's statistics.
    usage: /stats [player]
  credit:
    description: Shows how many credits you have.
    usage: /credit
  ArcherGames:
    description: Command for debugging.
    usage: /ArcherGames (subcmd)
  kit:
    description: Select a kit for the game
    usage: /kit (kitname)
    aliases: [kits]
  howlong:
    description: Tell you how long until something happens.
    usage: /howlong
  pay:
    description: Pay another player.
    usage: /pay <playertosentto> <amount>
    aliases: [givemoney]
  time:
    description: Show how much time is left in the game.
    usage: /time
    alises: [timeleft]
  timer:
    description: Set how much time is left in the game.
    usage: /timer <time in seconds>
  help:
    description: Get help.
    usage: /help
    aliases: [commands]
  goto:
    description: Teleport to a player while spectating
    usage: /goto (player)