name: ArcherGames
version: 0.1
main: com.araeosia.ArcherGames.ArcherGames
depend: [Vault, VanishNoPacket, Votifier, WorldBorder]

commands:
  vote:
    description: Displays the voting links to vote on.
    usage: /vote
  chunk:
    description: Reloads chunks to stop ghost blocks.
    usage: /chunk
  ride:
    description: Right click to sit on someone.
    usage: /ride
  chat:
    description: Disables or enables chat.
    usage: /chat
  track:
    description: Track player statistics.
    usage: /track <player>
  money:
    description: Checks wallet balance.
    usage: /money
  baltop:
    description: Shows the player with the most money.
    usage: /baltop
  credtop:
    description: Shows the player with the most credits.
    usage: /credtop
  stats:
    description: Shows a specified player's statistics.
    usage: /stats [player]
  credit:
    description: Shows how many credits you have.
    usage: /credit
  ArcherGames:
    description: Command for help, listing commands, and debugging.
    usage: /ArcherGames (help|commands)
  kit:
    description: Select a kit for the game
    usage: /kit (kitname)
  listkits:
    description: List avalible kits
    usage: /listkits
  howlong:
    description: Tell you how long until something happens.
    usage: /howlong
  pay:
    description: Pay another player.
    usage: /pay <playertosentto> <amount>
  time:
    description: Show how much time is left in the game.
    usage: /time
  timer:
    description: Set how much time is left in the game.
    usage: /timer <time in seconds>